services:
  web:
    build: .
    command: gunicorn wsgi:app --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      FLASK_ENV: development
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "${HOST_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
